### ISSUE TITLE
Order of layers sometimes wrong when initially loading indicator

### ISSUE THREAD

**Issue by lubojr** [eodash/eodash#102]
Order of layers for multiple collection indicator in the map is not deterministic and is encountering timing issues.

Example of collection: Polartep_S2_segmentation_demo

See video recording using the lib mode of eodash `npm run dev -- --lib`

https://github.com/user-attachments/assets/9d7c6269-6c2c-440a-8e25-b860b989341f

**Comment by A-Behairi** [comment]
moved to eox-a/eoxelements#1251
