### ISSUE TITLE
Integrate layer control

### ISSUE THREAD

**Issue by santilland** [eodash/eodash#47]
An initial decision will need to be made if we somehow need to wrap this as core component or if we can use it directly, in any case let's start by trying introducing the layer control and then experiment how to extend the "layer-config" options to support the style links of the stac items.

In respect to [layer config](https://eox-a.github.io/EOxElements/?path=/story/elements-eox-layercontrol--layer-config) here are some pointers from Silvester:
This is what currently is triggered when the eox-jsonform inside the layercontrol changes: https://github.com/EOX-A/EOxElements/blob/main/elements/layercontrol/src/components/layer-config.js#L92 (the entire layerconfig is currently hardcoded to do something with the layer tileUrlFunction, which only works with tile layers; we'd need some kind of check what moidification the layer config should perform, like modifying the tileUrlFunction, or modifying the vector style via styleexpression). Or we could check if the layer style exists and has variables, then assume that for this layer, the style variables are configurable, and otherwise we could fall back to modifying the tileUrlFunction.
A second point is that the jsonform outputs the state as defined in the schema, which could be nested (as for example vminmax.vmin and vminmax.vmax, but in the style it is called just vmin and vmax. I am not sure, either the style supports nested variables, or we need to come up with a way to define the output schema - maybe there is something already available at https://github.com/json-editor/json-editor. So, example, the schema is defined as vminmax.vmin and vminmax.vmax but the output is just vmin and vmax. Another option would be to change the custom vminmax input that we built at https://github.com/EOX-A/EOxElements/blob/main/elements/jsonform/src/custom-inputs/minmax.js.

We have style links that are expected to work for raster (COGs) and other for vector data, the concept is explained in the eodash.org docs.
Here is an example [style for cogs](https://github.com/eurodatacube/eodash-assets/blob/0f7790ca19bcf5524fcd887f6ad1449feb62fd4f/collections/D1_drought_vulnerability/flat_style.json)
Here is an example [style for vector](https://github.com/eurodatacube/eodash-assets/blob/0f7790ca19bcf5524fcd887f6ad1449feb62fd4f/collections/crop_forecast_CropOM/style_water_needed.json)

They are referenced as special style link in the stac item:
[for cog](https://eodashcatalog.eox.at/raw_source/trilateral/solar_energy/solar_energy/solar_energy/2023/2023.json)
[for vector ](https://eodashcatalog.eox.at/raw_source/RACE/CropModel_Forecast_Ind/crop_forecast_at_water/crop_forecast_at_water/2024/20240309.json)

the link has different types:
"text/vector-styles"
or
"text/cog-styles"

eodash v4 examples:
https://eodash-testing.eox.at/raw_source/?catalog=raw_source&indicator=CROPOMAT2
https://eodash-trilateral-testing.eox.at/raw_source/?catalog=raw_source
there is no actual stac extension for this so, we can use this to differentiate how to apply the style if needed

**Comment by lubojr** [comment]
@A-Behairi 

New URLs for eodash v4 examples after merges

https://eodash-staging.eox.at/?catalog=test-style&indicator=CROPOMAT2
https://eodash-trilateral-staging.eox.at/?catalog=test-style
