### ISSUE TITLE
Testing failing in github action, not locally

### ISSUE THREAD

**Issue by santilland** [eodash/eodash#53]

**Comment by A-Behairi** [comment]
Cypress is mistaking the [`eox-storytelling` markdown syntax string](https://github.com/eodash/eodash/actions/runs/10090139071/job/27898935177#step:5:32) used in `ExportState.vue` to be unterminated

**Comment by santilland** [comment]
That is inconvenient, not saying this is the best solution but at least a potential solution, trying to trick the parser to not identify it as something that needs to be terminated, we could modify:
https://github.com/eodash/eodash/blob/main/widgets/ExportState.vue#L91
from:
`"### <!--{ layers=";` to `"### <!"+"--{ layers=";`
could you give that a try?

**Comment by A-Behairi** [comment]
I think this might do it. It locally works, I'll test it with a PR.
